all: daytime.cpp echo.cpp
	g++ daytime.cpp ../socks.cpp -o daytime
	g++ echo.cpp ../socks.cpp -o echo
	g++ echo_cli.cpp ../socks.cpp -o echo_cli
	g++ multi_thread_server.cpp ../socks.cpp -o multi_thread_server
